version: '3.8'

services:
  thumbnail-api:
    platform: linux/amd64
    container_name: thumbnail-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:80"
    volumes:
      - ./output:/app/output
    environment:
      - entity_core_uri=http://host.docker.internal:8000
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
