[project]
name = "thumbnail_generation_api"
description = "Rest API to generate thumbnails"
version = "0.0.0"
authors = [{ name = "Blue Brain Project, EPFL" }]
readme = "README.md"
license = {text = "Apache-2.0"}
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115",
    "gunicorn>=23.0.0",
    "uvicorn>=0.30.6",
    "PyJWT>=2.8.0",
    "neurom>=4.0.2",
    "matplotlib>=3.7.4",
    "requests>=2.32.0",
    "python-dotenv>=1.0.0",
    "h5py>=3.11.0",
    "numpy>=2.1.0",
    "python-multipart>=0.0.9",
    "pydantic>=2.7.1",
    "pillow>=10.3.0",
    "httpx>=0.27.0",
    "sentry-sdk[fastapi]>=2.13.0",
    "pydantic-settings>=2.4.0",
    "plotly==5.23.0",
    "kaleido==0.2.1",  # for plotly
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11",
    "pyright>=1.1.401",
    "pytest>=8.3.2",
    "pytest-cov>=6.2.1",
]

[tool.ruff]
line-length = 100
target-version = "py312"
include = ["pyproject.toml", "api/**/*.py", "tests/**/*.py"]

[tool.ruff.lint]
preview = true
select = ["ALL"]
ignore = [
    "D",       # pydocstyle
    "ANN",     # All the annotations
    "COM812",  # Trailing comma (to have similar behavior to black)
    "CPY001",  # Missing copyright notice at top of file
    "DOC201",  # `return` is not documented in docstring
    "DOC402",  # `yield` is not documented in docstring
    "DOC501",  # Raised exception missing from docstring
    "ICN001",  # `matplotlib` should be imported as `mpl`
    "PLW2901", # `with` statement variable overwritten by assignment target
    "PLR2004", # Magic value used in comparison, consider replacing with a constant variable
    "RET504",  # Unnecessary assignment before `return` statement
    "RUF029",  # Function is declared `async`, but doesn't `await` or use `async` features.
    "TD",      # TODOs
    "FIX002",  # Line contains TODO, consider resolving the issue
    # to be fixed later
    "EM101",   # Exception must not use a string literal, assign to variable first
    "FAST002", # FastAPI dependency without `Annotated`
    "B008",    # Do not perform function call `Depends` in argument defaults
    "TRY003",  # Avoid specifying long messages outside the exception class
    "TRY301",  # Abstract `raise` to an inner function
    "RUF015",  # Prefer `next(iter())` over single element slice
    "PTH",     # `os.path` should be replaced by pathlib
    "SIM108",  # Use ternary operator
    "UP042",   # Class inherits from both `str` and `enum.Enum
]

[tool.ruff.lint.isort]
known-local-folder = ["tests"]
combine-as-imports = true

[tool.ruff.lint.per-file-ignores]
"tests/**.py" = [
    "ANN",     # Missing type annotation
    "ARG001",  # Unused function argument
    "ARG002",  # Unused method argument
    "ARG005",  # Unused lambda argument
    "D",       # pydocstyle
    "ERA001",  # Found commented-out code
    "INP001",  # Missing `__init__.py`
    "PLC2701", # Private name import from external module
    "PLR0913", # Too many arguments in function definition
    "PLR0915", # Too many statements
    "PLR0917", # Too many positional arguments
    "PLR2004", # magic value (constant) used in comparison (i.e. expected == 3)
    "PTH123",  # `open()` should be replaced by `Path.open()`
    "S101",    # Use of `assert` detected
    "SLF001",  # private member access
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "-vv",
    "-ra",
    "--cov=api",
    "--durations=10",
    "--durations-min=0.1",
]
# asyncio_mode = "auto"
testpaths = [
    "tests",
]

[tool.coverage.run]
branch = true
parallel = false
source_pkgs = [
    "api",
]

[tool.coverage.report]
show_missing = true
precision = 0
fail_under = 70
omit = [
]
