# pylint: disable=duplicate-code

"""
Module: plot_morphology.py

This module provides functionality for plotting neuronal morphology data using matplotlib.
"""

from neurom.view import matplotlib_impl, matplotlib_utils


def plot_morphology(morphology):
    """
    Creates and formats a matplotlib figure object.

    Parameters:
        - morphology: a morphology object as generated by neurom
    Returns:
        The matplotlib figure
    """
    fig, ax = matplotlib_utils.get_figure()

    matplotlib_impl.plot_morph(morphology, ax)

    ax.set_title("")
    ax.set_aspect("equal")
    ax.set_frame_on(False)
    ax.xaxis.set_visible(False)
    ax.yaxis.set_visible(False)
    bounds = ax.dataLim.bounds
    white_space = 0.05
    ax.set_xlim(bounds[0] - white_space, bounds[0] + bounds[2] + white_space)
    ax.set_ylim(bounds[1] - white_space, bounds[1] + bounds[3] + white_space)

    fig.set_layout_engine("tight")

    return fig
